# Generated by Django 4.1.6 on 2023-02-01 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ad',
            new_name='Ads',
        ),
    ]
